blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion / Questions
    url: https://github.com/Abhirup-261004/CareEase/discussions
    about: For general queries or ideas that aren’t clear issues yet.